name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # Grant write access to repository contents

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'
        fetch-depth: '0'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Clone destination repository
      run: |
        git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ae3f-devel/LogicFortress LogicFortress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Git
      run: |
        cd LogicFortress
        git config user.name "BOT"
        git config user.email "a@a.com"

    - name: Cleanup
      uses: JesseTG/rm@v1.0.3
      with:
        path: ./LogicFortress/Assets/Plugins

    - name: Git Add Cleanup
      run: |
        cd LogicFortress
        git add ./Assets/Plugins

    - name: Git Commit Cleanup
      run: |
        cd LogicFortress
        git commit -m "[CI/CD] Previous binaries removal"

    - name: Configure CMake
      run: |
        cmake -B LogicFortress/build -S LogicFortress -G Ninja

    - name: Build
      run: |
        cmake --build LogicFortress/build --config ${{ matrix.build_type }}

    - name: Git Add Build Output
      run: |
        cd LogicFortress
        git add ./Assets/

    - name: Git Commit Build
      run: |
        cd LogicFortress
        git commit -m "[CI/CD] Generated plugin build automation"

    - name: Push Changes
      run: |
        cd LogicFortress
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
