name: Build Command
on:
  push:
    branches: [main]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}  # Use your PAT
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ae3f-devel/LogicFortress/issues \
            -d '{"title":"[CI/CD] Automatic build command issue":"[Bare](https://github.com/ae3f-devel/Bare) has been updated: ","labels":["bug"]}'
